@extends('errors.layout')
@section('title', '429 - Too Many Requests')
@section('code', '429')
@section('heading', 'Too Many Requests')
@section('message', 'You have sent too many requests in a given amount of time.')