@extends('errors.layout')
@section('title', '500 - Internal Server Error')
@section('code', '500')
@section('heading', 'Internal Server Error')
@section('message', 'Something went wrong on our end. We are fixing it.')