@extends('errors.layout')
@section('title', '502 - Bad Gateway')
@section('code', '502')
@section('heading', 'Bad Gateway')
@section('message', 'The server received an invalid response from the upstream server.')